# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
    # 빌드한 jar 파일을 담을 디렉토리 생성
    - name: Create directory for delivery
      run: mkdir deploy
      
    # jar 파일 복사
    - name: Copy jar file
      run: cp ./build/libs/*.jar ./deploy/
      
    # 파일 압축
    - name: Create zip file
      run: zip -r -qq -j ./letshadow.zip ./deploy
      
    # s3로 zip 파일 전송
    - name: Send zip file to AWS S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{'{{' }} secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{'{{' }} secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./letshadow.zip s3://letshadow-deployer/


    
      
      
      
